### ISSUE TITLE
[Feature] Apply Pep-8 and other standards.

### ISSUE THREAD

**Issue by ycd** [spotify-api/spotify-api.py#2]
Since we are building a Python library it would be better if we use 4 spaces and using a code formatter like [Black](https://github.com/psf/black).

**Comment by abh80** [comment]
@Scientific-Guy make sure to check this issue in some hours.

**Comment by Scientific-Guy** [comment]
Yes i was actually using 4 spaces in visual studio code because i was using repl.it for testing it went messed up in indents so yes i will be making it 4 spaces in next updates

Thanks for the support too

**Comment by Scientific-Guy** [comment]
And yeah i will be using pep8 too in next update

**Comment by ycd** [comment]
Thanks @Scientific-Guy are you planning to add roadmap or smth like that?

**Comment by Scientific-Guy** [comment]
Well not for now i guess
Because i am currently a python learner still.
I will be updating it soon and secondly i use range() instead of using >= because people can even set things like -1 so range(50) will be range(0, 50)

I still don't know lot of python

**Comment by ycd** [comment]
Right, creating custom exceptions would be more appropriate, i 'll open a PR for it.

**Comment by Scientific-Guy** [comment]
Yeah lol. I am making it in my pc currently LEL
